// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk5O_4XHZVxOdGmRoxIkeh2X-pqauwy_E',
    appId: '1:354956638219:web:3fe4683f0e19fc0da32f0e',
    messagingSenderId: '354956638219',
    projectId: 'cyberguardian-c6830',
    authDomain: 'cyberguardian-c6830.firebaseapp.com',
    storageBucket: 'cyberguardian-c6830.firebasestorage.app',
    measurementId: 'G-3980FYXBMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOLUsFInecWUPjreI0FI3RQFxFIg4coqE',
    appId: '1:354956638219:android:beb73dba56fa3f42a32f0e',
    messagingSenderId: '354956638219',
    projectId: 'cyberguardian-c6830',
    storageBucket: 'cyberguardian-c6830.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsDpTzd6OTMX_sbT3XLZDNLk3x_Jt_Byg',
    appId: '1:354956638219:ios:f289e8c8bdf5e1dca32f0e',
    messagingSenderId: '354956638219',
    projectId: 'cyberguardian-c6830',
    storageBucket: 'cyberguardian-c6830.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsDpTzd6OTMX_sbT3XLZDNLk3x_Jt_Byg',
    appId: '1:354956638219:ios:f289e8c8bdf5e1dca32f0e',
    messagingSenderId: '354956638219',
    projectId: 'cyberguardian-c6830',
    storageBucket: 'cyberguardian-c6830.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk5O_4XHZVxOdGmRoxIkeh2X-pqauwy_E',
    appId: '1:354956638219:web:33b65a460bde2194a32f0e',
    messagingSenderId: '354956638219',
    projectId: 'cyberguardian-c6830',
    authDomain: 'cyberguardian-c6830.firebaseapp.com',
    storageBucket: 'cyberguardian-c6830.firebasestorage.app',
    measurementId: 'G-XY5J8J7KHT',
  );
}
